### ISSUE TITLE
其实我是想问一下，这游戏怎么玩啊？。。。

### ISSUE THREAD

**Issue by skyline75489** [yulingtianxia/ColorAtom#1]
进去之后不知道怎么就死了。。。

点了一下，出来四个球，然后一会儿又死了。。。

**Comment by yulingtianxia** [comment]
向上滑动发射正能量，向下滑动暂停游戏。每消灭一个负能量会获得三个正能量，如果没能拦截来袭的负能量，那么会损失一定的正能量。当正能量用光时游戏结束，所以游戏开始要反应迅速。游戏会在每关奖励一个“#”，它会分裂成四个正能量。

**Comment by skyline75489** [comment]
原来如此，还挺有意思的。

建议学长可以在第一次进入游戏的时候加个“玩法提示”之类的，不然真的不会玩。。。

直接点会不会好一点，比滑动要容易一点，上滑的话偶尔会出来控制中心。

**Comment by yulingtianxia** [comment]
过奖了，主要是一直在变换操作和玩法，相等最后定下来的时候再弄个玩法介绍，现在依然是个验证技术的demo。不用从屏幕底部上滑，任意地方上滑就可以。其实以前有长按连发功能，后来被我砍掉了。。。
